remove limit and bucket everything in other after 10 values
ClickHouse/clickpy pull request #116
Opened 2024-12-24 17:02 UTC by lio-p

Remove bucket limit on getDownloadsOverTimeByPython query

Group by Others when there is more than 10 values in the serie.

Close https://github.com/ClickHouse/clickpy/issues/105

2024-12-27 09:25 UTC, gingerwizard requested changes
see comments, we're dropping filters

2024-12-27 09:25 UTC, gingerwizard commented on src/utils/clickhouse.js
> +        AND 1=1 AND python_minor != ''
why these? why have we deleted the version, country_code and type features?

2024-12-27 09:25 UTC, gingerwizard commented on src/utils/clickhouse.js
> +                                WHERE (date >= {min_date:Date32}) AND (date < if(date_diff('month', {min_date:Date32},{max_date:Date32}) <= 6,toStartOfDay({max_date:Date32})::Date32, toStartOfWeek({m
this also needs filters for version, country_code and type

2025-01-06 14:27 UTC, lio-p commented on src/utils/clickhouse.js
> +                                WHERE (date >= {min_date:Date32}) AND (date < if(date_diff('month', {min_date:Date32},{max_date:Date32}) <= 6,toStartOfDay({max_date:Date32})::Date32, toStartOfWeek({m
fixed

2025-01-06 14:28 UTC, lio-p commented on src/utils/clickhouse.js
> +        AND 1=1 AND python_minor != ''
fixed

2025-01-07 11:46 UTC, merged